#docker-compose.yml

services:
  michael-cross:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # All NEXT_PUBLIC_* variables as build args
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        - NEXT_PUBLIC_IMAGE_URL=${NEXT_PUBLIC_IMAGE_URL}

    container_name: michael-cross
    restart: unless-stopped

    networks:
      - wazobiahms_app-network

networks:
  wazobiahms_app-network:
    external: true
