#docker-compose.prod.yml
services:
  michael-cross:
    # No need to specify build and args. They remains consistent across board if pecified in the docker-compose.yml (base file) .
    environment:
      # Runtime environment variables
      NODE_ENV: production
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      BETTER_AUTH_TRUST_HOST: ${BETTER_AUTH_TRUST_HOST}
      MONGO_URL: ${MONGO_URL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      CLOUDINARY_CLOUD_API_KEY: ${CLOUDINARY_CLOUD_API_KEY}
      CLOUDINARY_CLOUD_API_SECRET: ${CLOUDINARY_CLOUD_API_SECRET}
    container_name: michael-cross
    restart: unless-stopped

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email ${SSL_EMAIL} -d ${DOMAIN} ${DOMAIN_WITH_WWW} --agree-tos

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #     - ./certbot/conf:/etc/letsencrypt:ro
  #     - ./certbot/www:/var/www/certbot:ro
networks:
  app-network:
    external: true
