#docker-compose.yml

services:
  michael-cross:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # All NEXT_PUBLIC_* variables as build args
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
        - NEXT_PUBLIC_IMAGE_URL=${NEXT_PUBLIC_IMAGE_URL}

    container_name: michael-cross
    restart: unless-stopped

    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - app-network

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
    # ports:
    #   - "80:80"
    #   - "444:443"
    # No port since a site is already set up. Only include the new site to the nginx config
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./nginx/ssl:/etc/nginx/ssl:ro
    #   - ./certbot/conf:/etc/letsencrypt:ro
    #   - nginx_cache:/var/cache/nginx
    # depends_on:
    #   - michael-cross
    # networks:
    #   - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  # nginx_cache:
  #   driver: local
